/**
 * XXX
 * XXX
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddThingsCommandThings from './AddThingsCommandThings';

/**
 * The AddThingsCommand model module.
 * @module model/AddThingsCommand
 * @version 0.0.1
 */
class AddThingsCommand {
    /**
     * Constructs a new <code>AddThingsCommand</code>.
     * @alias module:model/AddThingsCommand
     */
    constructor() { 
        
        AddThingsCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddThingsCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddThingsCommand} obj Optional instance to populate.
     * @return {module:model/AddThingsCommand} The populated <code>AddThingsCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddThingsCommand();

            if (data.hasOwnProperty('things')) {
                obj['things'] = AddThingsCommandThings.constructFromObject(data['things']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddThingsCommand</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddThingsCommand</code>.
     */
    static validateJSON(data) {
        // validate the optional field `things`
        if (data['things']) { // data not null
          AddThingsCommandThings.validateJSON(data['things']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}



/**
 * @member {module:model/AddThingsCommandThings} things
 */
AddThingsCommand.prototype['things'] = undefined;

/**
 * @member {String} id
 * @default ''
 */
AddThingsCommand.prototype['id'] = '';






export default AddThingsCommand;

