/**
 * XXX
 * XXX
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ThingDto from './ThingDto';
import ThingDtoSubThing from './ThingDtoSubThing';

/**
 * The AddThingsCommandThings model module.
 * @module model/AddThingsCommandThings
 * @version 0.0.1
 */
class AddThingsCommandThings {
    /**
     * Constructs a new <code>AddThingsCommandThings</code>.
     * @alias module:model/AddThingsCommandThings
     * @param {(module:model/ThingDto)} instance The actual instance to initialize AddThingsCommandThings.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "ThingDto") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ThingDto.validateJSON(instance); // throw an exception if no match
                // create ThingDto from JS object
                this.actualInstance = ThingDto.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ThingDto
            errorMessages.push("Failed to construct ThingDto: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `AddThingsCommandThings` with oneOf schemas ThingDto. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `AddThingsCommandThings` with oneOf schemas ThingDto. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>AddThingsCommandThings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddThingsCommandThings} obj Optional instance to populate.
     * @return {module:model/AddThingsCommandThings} The populated <code>AddThingsCommandThings</code> instance.
     */
    static constructFromObject(data, obj) {
        return new AddThingsCommandThings(data);
    }

    /**
     * Gets the actual instance, which can be <code>ThingDto</code>.
     * @return {(module:model/ThingDto)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>ThingDto</code>.
     * @param {(module:model/ThingDto)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = AddThingsCommandThings.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of AddThingsCommandThings from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/AddThingsCommandThings} An instance of AddThingsCommandThings.
     */
    static fromJSON = function(json_string){
        return AddThingsCommandThings.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} property1
 */
AddThingsCommandThings.prototype['property1'] = undefined;

/**
 * @member {String} property2
 */
AddThingsCommandThings.prototype['property2'] = undefined;

/**
 * @member {module:model/ThingDtoSubThing} subThing
 */
AddThingsCommandThings.prototype['subThing'] = undefined;


AddThingsCommandThings.OneOf = ["ThingDto"];

export default AddThingsCommandThings;

