/**
 * XXX
 * XXX
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubThingDto from './SubThingDto';

/**
 * The ThingDtoSubThing model module.
 * @module model/ThingDtoSubThing
 * @version 0.0.1
 */
class ThingDtoSubThing {
    /**
     * Constructs a new <code>ThingDtoSubThing</code>.
     * @alias module:model/ThingDtoSubThing
     * @param {(module:model/SubThingDto)} instance The actual instance to initialize ThingDtoSubThing.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "SubThingDto") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                SubThingDto.validateJSON(instance); // throw an exception if no match
                // create SubThingDto from JS object
                this.actualInstance = SubThingDto.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into SubThingDto
            errorMessages.push("Failed to construct SubThingDto: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ThingDtoSubThing` with oneOf schemas SubThingDto. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ThingDtoSubThing` with oneOf schemas SubThingDto. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ThingDtoSubThing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingDtoSubThing} obj Optional instance to populate.
     * @return {module:model/ThingDtoSubThing} The populated <code>ThingDtoSubThing</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ThingDtoSubThing(data);
    }

    /**
     * Gets the actual instance, which can be <code>SubThingDto</code>.
     * @return {(module:model/SubThingDto)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>SubThingDto</code>.
     * @param {(module:model/SubThingDto)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ThingDtoSubThing.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ThingDtoSubThing from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/ThingDtoSubThing} An instance of ThingDtoSubThing.
     */
    static fromJSON = function(json_string){
        return ThingDtoSubThing.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Number} id
 */
ThingDtoSubThing.prototype['id'] = undefined;


ThingDtoSubThing.OneOf = ["SubThingDto"];

export default ThingDtoSubThing;

