/**
 * XXX
 * XXX
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Xxx);
  }
}(this, function(expect, Xxx) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Xxx.ThingDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ThingDto', function() {
    it('should create an instance of ThingDto', function() {
      // uncomment below and update the code to test ThingDto
      //var instance = new Xxx.ThingDto();
      //expect(instance).to.be.a(Xxx.ThingDto);
    });

    it('should have the property property1 (base name: "property1")', function() {
      // uncomment below and update the code to test the property property1
      //var instance = new Xxx.ThingDto();
      //expect(instance).to.be();
    });

    it('should have the property property2 (base name: "property2")', function() {
      // uncomment below and update the code to test the property property2
      //var instance = new Xxx.ThingDto();
      //expect(instance).to.be();
    });

    it('should have the property subThing (base name: "subThing")', function() {
      // uncomment below and update the code to test the property subThing
      //var instance = new Xxx.ThingDto();
      //expect(instance).to.be();
    });

  });

}));
